Fixing the pre-push script to fail when test fails

diff --git a/git-hooks/pre-push b/git-hooks/pre-push
--- a/git-hooks/pre-push
+++ b/git-hooks/pre-push
@@ -50,10 +50,12 @@ do
 	fi
 done
 
-test_result=`./gradlew test`
-echo "found test result $test_result"
-if [ $test_result -ne 0 ]; then
-        echo "failed building test"
-        exit 1
-    fi
-exit 0
+# run the tests with the gradle wrapper
+./gradlew test -q
+# Another possibility could be to run an aggregate test report task and automatically open the generated html
+
+# store the last exit code in a variable
+RESULT=$?
+
+# return the './gradlew test' exit code
+exit $RESULT
